# Generated by Django 3.0.5 on 2020-04-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcmanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tcmodule',
            options={'ordering': ['-create_time']},
        ),
        migrations.AddField(
            model_name='tcmodule',
            name='create_time',
            field=models.DateField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='tcmodule',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
