# Generated by Django 3.0.5 on 2020-04-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcmanage', '0002_auto_20200414_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='TcVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=20, verbose_name='版本名称')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
        migrations.AlterField(
            model_name='tcmodule',
            name='create_time',
            field=models.DateField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='tcmodule',
            name='module_name',
            field=models.CharField(max_length=20, verbose_name='模块名称'),
        ),
    ]
