# Generated by Django 3.0.5 on 2020-04-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcmanage', '0003_auto_20200418_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='TcUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('role', models.IntegerField(choices=[(0, '普通用户'), (1, '管理员')], verbose_name='角色')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.AlterField(
            model_name='tcmodule',
            name='module_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='模块名称'),
        ),
        migrations.AlterField(
            model_name='tcversion',
            name='version_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='版本名称'),
        ),
    ]
