# Generated by Django 3.0.5 on 2020-04-18 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tcmanage', '0004_auto_20200418_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='TcCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=50, verbose_name='用例名称')),
                ('tc_style', models.CharField(max_length=20, verbose_name='用例类型')),
                ('tc_level', models.IntegerField(verbose_name='用例等级')),
                ('tc_presetting', models.TextField(verbose_name='前置条件')),
                ('tc_steps', models.TextField(verbose_name='用例步骤')),
                ('tc_except_result', models.TextField(verbose_name='期望结果')),
                ('tc_actual_result', models.CharField(max_length=20, verbose_name='实际结果')),
                ('tc_comment', models.TextField(verbose_name='备注显示')),
                ('tc_user', models.CharField(max_length=20, verbose_name='分配人')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tc_module', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='module', to='tcmanage.TcModule')),
                ('tc_version', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='version', to='tcmanage.TcVersion')),
            ],
        ),
    ]
