# Generated by Django 3.0.5 on 2020-04-19 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tcmanage', '0005_tccase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tccase',
            options={'ordering': ['-create_time']},
        ),
        migrations.AlterField(
            model_name='tccase',
            name='tc_actual_result',
            field=models.CharField(choices=[('PASS', '通过'), ('FAIL', '失败'), ('BLOCK', '阻塞'), ('NA', '无法测试'), ('NotTest', '未测试')], default='NotTest', max_length=20, verbose_name='实际结果'),
        ),
        migrations.AlterField(
            model_name='tccase',
            name='tc_level',
            field=models.CharField(choices=[('SMOKING', '冒烟'), ('Function', 'LEVEL0'), ('LEVEL1', 'LEVEL1'), ('LEVEL2', 'LEVEL2')], default='SMOKING', max_length=20, verbose_name='用例等级'),
        ),
        migrations.AlterField(
            model_name='tccase',
            name='tc_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tcmanage.TcModule'),
        ),
        migrations.AlterField(
            model_name='tccase',
            name='tc_presetting',
            field=models.TextField(blank=True, verbose_name='前置条件'),
        ),
        migrations.AlterField(
            model_name='tccase',
            name='tc_style',
            field=models.CharField(choices=[('UI', 'UI'), ('Function', '功能'), ('Perfermance', '性能')], default='Function', max_length=20, verbose_name='用例类型'),
        ),
    ]
