# Generated by Django 3.0.5 on 2020-04-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcmanage', '0007_auto_20200419_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tccase',
            name='tc_comment',
            field=models.TextField(blank=True, verbose_name='备注显示'),
        ),
        migrations.AlterField(
            model_name='tccase',
            name='tc_level',
            field=models.CharField(choices=[('SMOKING', '冒烟'), ('LEVEL0', 'LEVEL0'), ('LEVEL1', 'LEVEL1'), ('LEVEL2', 'LEVEL2')], default='SMOKING', max_length=20, verbose_name='用例等级'),
        ),
    ]
